
########################################################################################
AUTOGENERATED HYPR CONFIG.
PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,
OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
########################################################################################


monitor=,1920x1080@60,0x0,1

input {
    kb_layout=
    kb_variant=
    kb_model=
    kb_options=
    kb_rules= 

    natural_scroll=1
    follow_mouse=1
}

general {
    max_fps=60 # deprecated, unused
    sensitivity=0.7
    main_mod=SUPER

    gaps_in=6
    gaps_out=15
    border_size=2
    col.active_border=0x9989dceb
    col.inactive_border=0x66333333

    damage_tracking=full # leave it on full unless you hate your GPU and want to make it suffer
}

exec=/home/cafo/.config/hypr/autostart.sh
exec-once=waybar
exec=wbg ~/Pictures/Wallpapers/ign_dudeOnBuilding.png

decoration {
    rounding=8
    blur=1
    blur_size=5 # minimum 1
    blur_passes=2 # minimum 1, more passes = more resource intensive.
    # Your blur "amount" is blur_size * blur_passes, but high blur_size (over around 5-ish) will produce artifacts.
    # if you want heavy blur, you need to up the blur_passes.
    # the more passes, the more you can up the blur_size without noticing artifacts.
}

animations {
    enabled=1
    animation=windows,1,7,default
    animation=borders,1,10,default
    animation=fadein,1,10,default
    animation=workspaces,1,6,default
}

dwindle {
    pseudotile=0 # enable pseudotiling on dwindle
}

# example window rules
# for windows named/classed as abc and xyz
#windowrule=move 69 420,abc
# windowrule=size 420 69,spotify
#windowrule=tile,xyz
windowrule=float,Signal Beta
#windowrule=pseudo,abc
#windowrule=monitor 0,xyz
windowrule=workspace 2,Firefox
windowrule=workspace 4,Discord

# SHORTCUTS
bind=,XF86AudioLowerVolume,exec,pamixer -d 5
bind=,XF86AudioRaiseVolume,exec,pamixer -i 5
bind=,XF86AudioMute,exec,pamixer -t
bind=,XF86AudioMicMute,exec,mictoggle

bind=,XF86AudioPlay,exec,playerctl play-pause
bind=,XF86AudioNext,exec,playerctl next
bind=,XF86AudioPrev,exec,playerctl previous
bind=,XF86AudioStop,exec,playerctl stop

bind=,XF86MonBrightnessUp,exec,light -A 5
bind=,XF86MonBrightnessDown,exec,light -U 5

#

bind=SUPERSHIFT,X,exec,poweroff
bind=SUPERSHIFT,Q,exec,killall Hyprland
bind=SUPER,KP_Subtract,exec,wayblur


bind=SUPER,RETURN,exec,kitty
bind=SUPER,KP_Return,exec,kitty
bind=SUPER,V,exec,pavucontrol
bind=SUPER,E,exec,emacs
bind=SUPERSHIFT,SPACE,exec,nautilus
bind=,PRINT,exec,grimshot
bind=SHIFT,PRINT,exec,grimclip
bind=SUPER,PRINT,exec,grimcrop

bind=SUPER,B,exec,killall -SIGUSR1 waybar

# example binds
bind=SUPER,D,exec,rofi -show drun
bind=SUPER,R,exec,rofi -show run

bind=SUPER,Q,killactive,

bind=SUPER,L,splitratio,+
bind=SUPER,H,splitratio,-

bind=SUPERSHIFT,LEFT,movewindow,l
bind=SUPERSHIFT,RIGHT,movewindow,r
bind=SUPERSHIFT,UP,movewindow,u
bind=SUPERSHIFT,DOWN,movewindow,d

bind=SUPER,LEFT,movefocus,l
bind=SUPER,RIGHT,movefocus,r
bind=SUPER,UP,movefocus,u
bind=SUPER,DOWN,movefocus,d
bind=SUPER,F,togglefloating
bind=SUPER,S,togglespecialworkspace
bind=SUPER,W,fullscreen,

bind=SUPER,1,workspace,1
bind=SUPER,2,workspace,2
bind=SUPER,3,workspace,3
bind=SUPER,4,workspace,4
bind=SUPER,5,workspace,5
bind=SUPER,6,workspace,6
bind=SUPER,7,workspace,7
bind=SUPER,8,workspace,8
bind=SUPER,9,workspace,9

bind=ALT,1,movetoworkspace,1
bind=ALT,2,movetoworkspace,2
bind=ALT,3,movetoworkspace,3
bind=ALT,4,movetoworkspace,4
bind=ALT,5,movetoworkspace,5
bind=ALT,6,movetoworkspace,6
bind=ALT,7,movetoworkspace,7
bind=ALT,8,movetoworkspace,8
bind=ALT,9,movetoworkspace,9
bind=ALT,S,movetoworkspace,special
